/* The waiters need to have access to the new software, so they need personal accounts. Your task is to generate their usernames and passwords.
Write a query that returns: the username and password for all waiters who are not fired (a fired waiter is a waiter without salary). The username is generated by their last name immediately followed by their first name followed by the number of characters from first name and at the end "Restaurant". The password is their email starting from the 2nd character to the 13th character and then reversed.
Order by password in descending order.
Required Columns:
    • username (last_name + first_name + characters count from first_name + "Restaurant")
    • password (starting from the 2nd character to the 13th character of their email and then reversed) */